version: '3.8'

services:
  # Docker镜像代理服务
  docker-transformer:
    image: ghcr.io/cflmflj/docker-transformer:latest
    container_name: docker-transformer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=release
      - LOG_LEVEL=info
      - DB_PATH=/app/data/proxy.db
      - DEFAULT_TOKEN=docker-transformer
      - TZ=Asia/Shanghai
    volumes:
      # 数据持久化卷
      - transformer_data:/app/data
      # Docker socket挂载（用于Docker操作）
      - /var/run/docker.sock:/var/run/docker.sock
    # 使用root用户运行以确保Docker socket访问权限
    user: "0:0"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  # 数据持久化卷
  transformer_data:
    driver: local 